headerScanLimit: 50
headerValueScanLimit: 30
captureExtraColumns: true
# groupIdFieldNames: ["groupid"]
# occurrenceFieldNames: ["occurenceCount", "occurrenceCount"]
requiredColumns: ["SEG_LVL", "FIELD_NAME", "DESCRIPTION", "LENGTH", "DATATYPE"]
maxConsecutiveEmptyRows: 5
# columnAliases:
#   segLvl: ["Seg lvl", "Segment Level"]
#   fieldName: ["Field Name"]
#   description: ["Description", "Desc"]
#   length: ["Length"]
#   datatype: ["Messaging Datatype", "Datatype"]
#   opt: ["Opt(O/M)"]
#   nullable: ["Null(Y/N)"]
#   sample: ["Sample Value(s)"]
