server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mqtool:
  baseDir: schema-repo-example
  basePackage: com.rtm.mq.generated
  groupIdMode: STRICT
  maxUploadSizeMb: 50
  # xmlTemplatePath: /path/to/converter-xml.ftl
  protocol:
    groupIdFieldName: groupid
    occurrenceFieldName: occurenceCount
    groupIdLength: 10
    occurrenceLength: 4
    byteOrder: BIG_ENDIAN
