server:
  port: 8080

mqtool:
  baseDir: schema-repo-example
  basePackage: com.rtm.mq.generated
  groupIdMode: STRICT
  # xmlTemplatePath: /path/to/converter-xml.ftl
  protocol:
    groupIdFieldName: groupid
    occurrenceFieldName: occurenceCount
    groupIdLength: 10
    occurrenceLength: 4
    byteOrder: BIG_ENDIAN
